# Generated by Django 6.0.4 on 2026-05-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='captured_images/'),
        ),
    ]
